/**
 * endpoints.js
 * Registro de endpoints (config) — Fase 4: componente genérico. Cada objeto
 * descreve tudo que a UI precisa para montar o card, o formulário de
 * parâmetros e a chamada, sem HTML específico por endpoint.
 *
 * `category`/`categoryLabel` agrupam os endpoints na sidebar (js/explorer.js
 * monta um grupo por categoria dinamicamente — nada de HTML fixo por grupo).
 *
 * Todos os endpoints de listagem abaixo foram confirmados no spec OpenAPI da
 * própria API como tendo exatamente o mesmo formato de parâmetros (page, q,
 * order, orderby, filter) — o mesmo padrão já validado ponta a ponta em
 * GET /v1/regioes (Fase 3), incluindo o header `Authorization: Bearer`.
 */

// Params compartilhados por todos os endpoints de listagem/paginação da API.
const TGA_LIST_PARAMS = [
  { name: 'page', label: 'Página', type: 'number', default: 1, min: 1 },
  { name: 'q', label: 'Registros por página', type: 'number', default: 50, min: 1 },
  {
    name: 'order',
    label: 'Ordenação',
    type: 'select',
    options: [
      { value: '', label: '—' },
      { value: 'ASC', label: 'Ascendente' },
      { value: 'DESC', label: 'Decrescente' },
    ],
  },
  { name: 'orderby', label: 'Campo de ordenação', type: 'text', placeholder: 'ex: DESCRICAO' },
  { name: 'filter', label: 'Filtro', type: 'text', placeholder: 'ex: CAMPO:eq(valor)', wide: true },
];

/** Clona TGA_LIST_PARAMS trocando só o valor padrão do campo "filter" (igual ao Swagger, que já vem pré-preenchido nesses 2 endpoints de config). */
function listParamsWithFilterDefault(defaultFilter) {
  return TGA_LIST_PARAMS.map(p => (p.name === 'filter' ? { ...p, default: defaultFilter } : p));
}

// Variante sem o campo "filter" — vários endpoints de sub-recurso de cliente/
// produto (ex.: pedidos, status-financeiro, regras-preco) só têm page/q/order/orderby no spec.
const TGA_LIST_PARAMS_NO_FILTER = TGA_LIST_PARAMS.filter(p => p.name !== 'filter');

const TGA_ENDPOINTS = [
  {
    id: 'status',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Status',
    method: 'GET',
    path: '/status',
    title: 'Retorna o status atual da API',
    description: 'Endpoint de verificação de disponibilidade. Não exige autenticação na prática (confirmado ' +
      'empiricamente — mesmo o spec listando "security" para esta rota).',
    requiresAuth: false,
    params: [],
  },
  {
    id: 'regioes',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Regiões',
    method: 'GET',
    path: '/regioes',
    title: 'Retorna uma lista de regiões',
    description: 'Miscelânea — conjunto de tabelas auxiliares. Primeiro endpoint validado ponta a ponta (Fase 3).',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'portadores',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Portadores',
    method: 'GET',
    path: '/portadores',
    title: 'Retorna uma lista de portadores',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'condicoes-pagamento',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Condições de pagamento',
    method: 'GET',
    path: '/condicoes-pagamento',
    title: 'Retorna uma lista das condições de pagamento',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'vendedores',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Vendedores',
    method: 'GET',
    path: '/vendedores',
    title: 'Retorna uma lista de vendedores',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'representantes',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Representantes',
    method: 'GET',
    path: '/representantes',
    title: 'Retorna uma lista de representantes',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'tipos-objeto',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Tipos de objeto',
    method: 'GET',
    path: '/tipos-objeto',
    title: 'Retorna uma lista de tipos de objeto do cliente',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'tipos-movimento',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Tipos de movimento',
    method: 'GET',
    path: '/tipos-movimento',
    title: 'Retorna uma lista de tipos de movimento',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'promocoes',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Promoções',
    method: 'GET',
    path: '/promocoes',
    title: 'Retorna uma lista de promoções',
    description: 'Miscelânea — conjunto de tabelas auxiliares.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'alteracoes-get',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Alterações (consultar)',
    method: 'GET',
    path: '/alteracoes',
    title: 'Retorna uma lista de registros alterados a serem sincronizados',
    description: 'Miscelânea — conjunto de tabelas auxiliares. Parâmetros diferentes dos demais (sem order/orderby/filter).',
    requiresAuth: true,
    params: [
      { name: 'page', label: 'Página', type: 'number', default: 1, min: 1 },
      { name: 'q', label: 'Registros por página', type: 'number', default: 50, min: 1 },
      { name: 'tabela', label: 'Tabela', type: 'text', placeholder: 'ex: PRODUTO' },
    ],
  },
  {
    id: 'alteracoes-put',
    category: 'misc',
    categoryLabel: 'Misc',
    menuLabel: 'Alterações (confirmar sync)',
    method: 'PUT',
    path: '/alteracoes',
    title: 'Informa o servidor que o registro já foi sincronizado',
    description: 'Miscelânea — conjunto de tabelas auxiliares. Resposta de sucesso é 204 (sem corpo).',
    requiresAuth: true,
    params: [],
    body: { ORIGEM: 'PRODUTO', CHAVE: '000001' },
  },

  // ---------------- Configurações — TGA ERP ----------------

  {
    id: 'config-parametros',
    category: 'config',
    categoryLabel: 'Configurações',
    menuLabel: 'Parâmetros',
    method: 'GET',
    path: '/config/parametros',
    title: 'Retorna uma lista de parâmetros',
    description: 'Configurações — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'config-empresas',
    category: 'config',
    categoryLabel: 'Configurações',
    menuLabel: 'Empresas',
    method: 'GET',
    path: '/config/empresas',
    title: 'Retorna dados da empresa',
    description: 'Configurações — TGA ERP.',
    requiresAuth: true,
    // No Swagger, o filtro já vem pré-preenchido com a empresa 1 por padrão.
    params: listParamsWithFilterDefault('CODEMPRESA:eq(1)'),
  },
  {
    id: 'config-filiais',
    category: 'config',
    categoryLabel: 'Configurações',
    menuLabel: 'Filiais',
    method: 'GET',
    path: '/config/filiais',
    title: 'Retorna dados das filiais',
    description: 'Configurações — TGA ERP.',
    requiresAuth: true,
    // No Swagger, o filtro já vem pré-preenchido com a filial 1 por padrão.
    params: listParamsWithFilterDefault('CODFILIAL:eq(1)'),
  },

  // ---------------- Clientes — TGA ERP ----------------

  {
    id: 'clientes-post',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Cadastrar/atualizar',
    method: 'POST',
    path: '/clientes',
    title: 'Cadastrar ou atualizar um cadastro de cliente existente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    params: [],
    body: {
      NOMEFANTASIA: '', NOME: '', PESSOAFISJUR: 'F', RUA: '', NUMERO: '', BAIRRO: '',
      COMPLEMENTO: '', CIDADE: '', IDCIDADE: 0, CODETD: 'MT', CEP: '', CONTATO: '',
      TELEFONE: '', TELEFONE2: '', FAX: '', INDICADORIE: '', INSCRESTADUAL: '',
      CGCCFO: '', EMAIL: '', CI_NUMERO: '', CI_ORGAO: '', CI_UF: '', DTAEMISAORG: '',
    },
  },
  {
    id: 'clientes-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Listar clientes',
    method: 'GET',
    path: '/clientes',
    title: 'Retorna uma lista de clientes',
    description: 'Clientes — TGA ERP. Por padrão, retorna 100 registros por página.',
    requiresAuth: true,
    params: [
      { name: 'page', label: 'Página', type: 'number', default: 1, min: 1 },
      { name: 'q', label: 'Registros por página', type: 'number', default: 50, min: 1 },
      {
        name: 'order', label: 'Ordenação', type: 'select',
        options: [{ value: '', label: '—' }, { value: 'ASC', label: 'Ascendente' }, { value: 'DESC', label: 'Decrescente' }],
      },
      { name: 'orderby', label: 'Campo de ordenação', type: 'text', placeholder: 'ex: NOME' },
      {
        name: 'retornaFinanceiro', label: 'Retornar informações financeiras', type: 'select',
        options: [{ value: 'true', label: 'Sim' }, { value: 'false', label: 'Não' }], default: 'true',
      },
      { name: 'filter', label: 'Filtro', type: 'text', placeholder: 'ex: CAMPO:eq(valor)', wide: true },
    ],
  },
  {
    id: 'clientes-objetos-post',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Cadastrar objeto',
    method: 'POST',
    path: '/clientes/objetos',
    title: 'Cadastrar objeto para um cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    params: [],
    body: {
      NUMEROSERIE: '', CODCFO: '', CODTIPO: '', MODELO: '', ANO: '', COR: '',
      OBS: '', CODAUXILIAR: '', PESO: 10,
    },
  },
  {
    id: 'clientes-objetos-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Listar objetos',
    method: 'GET',
    path: '/clientes/objetos',
    title: 'Retorna uma lista de objetos dos clientes',
    description: 'Clientes — TGA ERP. Por padrão, retorna 50 registros por página.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'clientes-objeto-imagens-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Imagens do objeto',
    method: 'GET',
    path: '/clientes/objetos/{idObjeto}/imagens',
    title: 'Retorna uma lista de imagens de um objeto',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idObjeto', label: 'ID do objeto', placeholder: 'ex: 123' }],
    params: [],
  },
  {
    id: 'clientes-objeto-imagens-post',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Adicionar imagem ao objeto',
    method: 'POST',
    path: '/clientes/objetos/{idObjeto}/imagens',
    title: 'Adicionar imagem para um objeto',
    description: 'Clientes — TGA ERP. A imagem deve ser enviada em base64 no campo IMAGEM.',
    requiresAuth: true,
    pathParams: [{ name: 'idObjeto', label: 'ID do objeto', placeholder: 'ex: 123' }],
    params: [],
    body: { IMAGEM: '' },
  },
  {
    id: 'clientes-objeto-imagem-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Imagem do objeto por ID',
    method: 'GET',
    path: '/clientes/objetos/{idObjeto}/imagens/{idImagem}',
    title: 'Retorna uma imagem de um objeto pelo ID',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [
      { name: 'idObjeto', label: 'ID do objeto', placeholder: 'ex: 123' },
      { name: 'idImagem', label: 'ID da imagem', placeholder: 'ex: 1' },
    ],
    params: [],
  },
  {
    id: 'clientes-visita-post',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Cadastrar visita',
    method: 'POST',
    path: '/clientes/{codcfo}/visita',
    title: 'Cadastrar visita para um cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'codcfo', label: 'Código do cliente', placeholder: 'ex: C00001' }],
    params: [],
    body: {
      CODCFO: '', CODEMPRESA: 1, LATITUDE: -14.618650331763993, LONGITUDE: -57.48834973522729,
      CODVEN: '', DATACRIACAO: '', ID_PROP: 1, OBS: '',
    },
  },
  {
    id: 'clientes-imagens-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Imagens do cliente',
    method: 'GET',
    path: '/clientes/{codcfo}/imagens',
    title: 'Retorna uma lista de imagens do cliente',
    description: 'Clientes — TGA ERP. Atenção: esta rota pode ficar lenta dependendo do tamanho/quantidade de imagens do cliente.',
    requiresAuth: true,
    pathParams: [{ name: 'codcfo', label: 'Código do cliente', placeholder: 'ex: C00001' }],
    params: TGA_LIST_PARAMS_NO_FILTER,
  },
  {
    id: 'clientes-pedidos-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Pedidos do cliente',
    method: 'GET',
    path: '/clientes/{codcfo}/pedidos',
    title: 'Retorna as últimas 10 vendas do cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'codcfo', label: 'Código do cliente', placeholder: 'ex: C00001' }],
    params: TGA_LIST_PARAMS_NO_FILTER,
  },
  {
    id: 'clientes-status-financeiro-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Status financeiro',
    method: 'GET',
    path: '/clientes/{codcfo}/status-financeiro',
    title: 'Retorna a situação financeira de um cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'codcfo', label: 'Código do cliente', placeholder: 'ex: C00001' }],
    params: TGA_LIST_PARAMS_NO_FILTER,
  },
  {
    id: 'clientes-lancamentos-financeiros-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Lançamentos financeiros',
    method: 'GET',
    path: '/clientes/{codcfo}/lancamentos-financeiros',
    title: 'Retorna os lançamentos financeiros de um cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'codcfo', label: 'Código do cliente', placeholder: 'ex: C00001' }],
    params: listParamsWithFilterDefault('STATUSLAN:eq(A)'),
  },
  {
    id: 'clientes-boletos-get',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Boletos em aberto',
    method: 'GET',
    path: '/clientes/{cgccfo}/boletos',
    title: 'Retorna os boletos mais antigos em aberto de um cliente',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'cgccfo', label: 'CPF/CNPJ (somente números)', placeholder: 'ex: 00000000000' }],
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'tipos-cliente',
    category: 'clientes',
    categoryLabel: 'Clientes',
    menuLabel: 'Tipos de cliente',
    method: 'GET',
    path: '/tipos-cliente',
    title: 'Retorna uma lista de tabelas de preço com produtos',
    description: 'Clientes — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },

  // ---------------- Propriedades — TGA ERP ----------------

  {
    id: 'propriedades-get',
    category: 'propriedades',
    categoryLabel: 'Propriedades',
    menuLabel: 'Listar propriedades',
    method: 'GET',
    path: '/propriedades',
    title: 'Retorna uma lista de propriedades',
    description: 'Propriedades — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'propriedades-put',
    category: 'propriedades',
    categoryLabel: 'Propriedades',
    menuLabel: 'Atualizar propriedade',
    method: 'PUT',
    path: '/propriedades/{id_prop}',
    title: 'Atualizar um cadastro de propriedade existente',
    description: 'Propriedades — TGA ERP. Resposta de sucesso é 204 (sem corpo).',
    requiresAuth: true,
    pathParams: [{ name: 'id_prop', label: 'ID do cadastro de propriedade', placeholder: 'ex: 1' }],
    params: [],
    body: { LATITUDE: '', LONGITUDE: '' },
  },

  // ---------------- Produtos — TGA ERP ----------------

  {
    id: 'produtos-get',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Listar produtos',
    method: 'GET',
    path: '/produtos',
    title: 'Retorna uma lista de produtos',
    description: 'Produtos — TGA ERP. Por padrão, retorna 100 registros por página.',
    requiresAuth: true,
    params: [
      {
        name: 'fracionado', label: 'Somente fracionados', type: 'select',
        options: [{ value: 'false', label: 'Não' }, { value: 'true', label: 'Sim' }], default: 'false',
      },
      {
        name: 'tipoitem', label: 'Tipo de item (SPED)', type: 'select',
        options: [
          { value: '', label: '—' },
          { value: '00', label: '00 - Mercadoria p/ Revenda' },
          { value: '01', label: '01 - Matéria-Prima' },
          { value: '02', label: '02 - Embalagem' },
          { value: '03', label: '03 - Produto em Processo' },
          { value: '04', label: '04 - Produto Acabado' },
          { value: '05', label: '05 - Sub-Produto' },
          { value: '06', label: '06 - Produto Intermediário' },
          { value: '07', label: '07 - Material Uso/Consumo' },
          { value: '08', label: '08 - Ativo Imobilizado' },
          { value: '09', label: '09 - Serviços' },
          { value: '99', label: '99 - Outras' },
        ],
      },
      { name: 'page', label: 'Página', type: 'number', default: 1, min: 1 },
      { name: 'q', label: 'Registros por página', type: 'number', default: 50, min: 1 },
      {
        name: 'order', label: 'Ordenação', type: 'select',
        options: [{ value: '', label: '—' }, { value: 'ASC', label: 'Ascendente' }, { value: 'DESC', label: 'Decrescente' }],
      },
      { name: 'orderby', label: 'Campo de ordenação', type: 'text', placeholder: 'ex: DESCRICAO' },
      { name: 'filter', label: 'Filtro', type: 'text', placeholder: 'ex: CAMPO:eq(valor)', wide: true },
    ],
  },
  {
    id: 'produtos-regras-preco-get',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Regras de preço',
    method: 'GET',
    path: '/produtos/{codprd}/regras-preco',
    title: 'Retorna uma lista de regras de preço de um produto',
    description: 'Produtos — TGA ERP. Por padrão, retorna 50 registros por página.',
    requiresAuth: true,
    pathParams: [{ name: 'codprd', label: 'Código do produto', placeholder: 'ex: 000001' }],
    params: TGA_LIST_PARAMS_NO_FILTER,
  },
  {
    id: 'produtos-imagens-get',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Imagens do produto',
    method: 'GET',
    path: '/produtos/{codprd}/imagens',
    title: 'Retorna uma lista de imagens do produto informado',
    description: 'Produtos — TGA ERP. Atenção: esta rota pode ficar lenta dependendo do tamanho/quantidade de imagens do produto.',
    requiresAuth: true,
    pathParams: [{ name: 'codprd', label: 'Código do produto', placeholder: 'ex: 000001' }],
    params: [],
  },
  {
    id: 'tabelas-preco',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Tabelas de preço',
    method: 'GET',
    path: '/tabelas-preco',
    title: 'Retorna uma lista de tabelas de preço com produtos',
    description: 'Produtos — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'grupos-get',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Grupos de produto',
    method: 'GET',
    path: '/grupos',
    title: 'Retorna uma lista dos grupos de produto',
    description: 'Produtos — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'grupos-imagens-get',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Imagens do grupo',
    method: 'GET',
    path: '/grupos/{codgrupo}/imagens',
    title: 'Retorna uma lista de imagens de um grupo',
    description: 'Produtos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'codgrupo', label: 'Código do grupo', placeholder: 'ex: 001' }],
    params: TGA_LIST_PARAMS_NO_FILTER,
  },
  {
    id: 'fabricantes',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Fabricantes',
    method: 'GET',
    path: '/fabricantes',
    title: 'Retorna uma lista de fabricantes',
    description: 'Produtos — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'tipos-produto',
    category: 'produtos',
    categoryLabel: 'Produtos',
    menuLabel: 'Tipos de produto',
    method: 'GET',
    path: '/tipos-produto',
    title: 'Retorna uma lista dos tipos de produto',
    description: 'Produtos — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },

  // ---------------- Movimentos — TGA ERP ----------------

  {
    id: 'movimentos-post',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Enviar novo pedido',
    method: 'POST',
    path: '/movimentos',
    title: 'Enviar um NOVO pedido para o servidor',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    params: [],
    body: {
      CODEMPRESA: 1, CODFILIAL: 1, CODCFO: 'C00001', CODTMV: '2.2.03', IDMOVMOBILE: 789,
      DATAEMISSAO: '2024-02-08', NOMECONSUMIDOR: 'string', CODTABPRECO: 'string',
      CODPORTADOR: 'string', CODCPG: '01', CODVEN: '001', CODRPR: '001', ID_PROP: 0,
      PERCENTUALDESC: 10.5, VALORBRUTO: 1000, VALORFRETE: 50, PERCENTUALFRETE: 5,
      VALORDESC: 100, VALORDESP: 20, PERCENTUALDESP: 2, VALORLIQUIDO: 870,
      VALORSEMPROMOCAO: 1200, VALORSEGURO: 15, PERCENTUALSEGURO: 1.5,
      VALOREXTRA1: 0, PERCENTUALEXTRA1: 0, VALOREXTRA2: 0, PERCENTUALEXTRA2: 0,
      VALOREXTRA3: 0, PERCENTUALEXTRA3: 0, VALOREXTRA4: 0, PERCENTUALEXTRA4: 0,
      OBSERVACAO: '', LATITUDE: '-23.550520', LONGITUDE: '-46.633308',
      itens: [{
        NSEQ: 1, CODPRD: '000001', NOMEFANTASIA: null, NUMNOFABRIC: null, CODUND: 'UN',
        QUANTIDADE: 1, PRECOUNITARIO: 100, VALORTOTALITEM: 0, VALORDESP: 100, VALORDESC: 0,
        PERCENTUALDESC: 100, IDPROMOCAO: 0, CAMPOLIVRE: null, OBSERVACAO: null,
        PRECOTABELA: 100, TOTALITEM: 100, PRECOUNITARIOSELEC: 0, PRECOTABELAALTERADO: false,
      }],
    },
  },
  {
    id: 'movimentos-get',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Listar movimentos',
    method: 'GET',
    path: '/movimentos',
    title: 'Retorna dados dos movimentos',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    params: listParamsWithFilterDefault('CODTMV:eq(2.2.03)|CODCFO:eq(C00001)'),
  },
  {
    id: 'movimentos-status-get',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Status do pedido',
    method: 'GET',
    path: '/movimentos/{idmov}/status',
    title: 'Retorna o status de um pedido',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
  },
  {
    id: 'movimentos-status-post',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Adicionar status',
    method: 'POST',
    path: '/movimentos/{idmov}/status',
    title: 'Adicionar um novo status para um movimento',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
    body: { STATUSOS: '', OBSERVACAO: '' },
  },
  {
    id: 'movimentos-imagens-post',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Enviar imagem',
    method: 'POST',
    path: '/movimentos/{idmov}/imagens',
    title: 'Enviar uma nova imagem para um movimento',
    description: 'Movimentos — TGA ERP. A imagem deve ser enviada em base64 no campo IMAGEM.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
    body: { IMAGEM: '' },
  },
  {
    id: 'movimentos-imagens-get',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Imagens do pedido',
    method: 'GET',
    path: '/movimentos/{idmov}/imagens',
    title: 'Retorna as imagens de um pedido',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
  },
  {
    id: 'movimentos-imagem-get',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Imagem por ID',
    method: 'GET',
    path: '/movimentos/{idmov}/imagens/{id}',
    title: 'Retorna uma imagem por ID',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [
      { name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' },
      { name: 'id', label: 'ID da imagem', placeholder: 'ex: 1' },
    ],
    params: [],
  },
  {
    id: 'movimentos-alteracao-vendedor-post',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Lançar alteração de vendedor',
    method: 'POST',
    path: '/movimentos/{idmov}/alteracao-vendedor',
    title: 'Lançar alteração de vendedor de um movimento',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
    body: { CODVENDANTERIOR: '', CODVENDNOVO: '', OBSERVACAO: '' },
  },
  {
    id: 'movimentos-alteracao-vendedor-get',
    category: 'movimentos',
    categoryLabel: 'Movimentos',
    menuLabel: 'Alterações de vendedor',
    method: 'GET',
    path: '/movimentos/{idmov}/alteracao-vendedor',
    title: 'Retorna as alterações de vendedor de um movimento',
    description: 'Movimentos — TGA ERP.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'IDMOV do pedido', placeholder: 'ex: 1' }],
    params: [],
  },

  // ---------------- Ordem de Serviço — TGA ERP ----------------

  {
    id: 'status-os',
    category: 'ordem-servico',
    categoryLabel: 'Ordem de Serviço',
    menuLabel: 'Status de OS',
    method: 'GET',
    path: '/status-os',
    title: 'Retorna uma lista de status de ordens de serviço',
    description: 'Ordem de Serviço — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },

  // ---------------- Checklist — TGA ERP ----------------

  {
    id: 'checklist-get',
    category: 'checklist',
    categoryLabel: 'Checklist',
    menuLabel: 'Tipos de checklist',
    method: 'GET',
    path: '/checklist',
    title: 'Retorna uma lista de tipos de checklist e suas respectivas dependências',
    description: 'Checklist — TGA ERP.',
    requiresAuth: true,
    params: TGA_LIST_PARAMS,
  },
  {
    id: 'checklist-resposta-post',
    category: 'checklist',
    categoryLabel: 'Checklist',
    menuLabel: 'Responder pergunta',
    method: 'POST',
    path: '/movimentos/{idmov}/checklist',
    title: 'Inserir a resposta de uma pergunta do checklist para um movimento',
    description: 'Checklist — TGA ERP. A imagem (se houver) deve ser enviada em base64 no campo IMAGEM.',
    requiresAuth: true,
    pathParams: [{ name: 'idmov', label: 'ID do movimento', placeholder: 'ex: 1' }],
    params: [],
    body: { IDCHECKLISTPERGUNTA: 1, IDCHECKLISTRESPOSTA: 1, IMAGEM: '' },
  },
  {
    id: 'checklist-resposta-delete',
    category: 'checklist',
    categoryLabel: 'Checklist',
    menuLabel: 'Deletar resposta',
    method: 'DELETE',
    path: '/movimentos/{idmov}/checklist/{id}',
    title: 'Deletar uma resposta do checklist',
    description: 'Checklist — TGA ERP. Resposta de sucesso é 204 (sem corpo).',
    requiresAuth: true,
    pathParams: [
      { name: 'idmov', label: 'ID do movimento', placeholder: 'ex: 1' },
      { name: 'id', label: 'ID da resposta do checklist', placeholder: 'ex: 1' },
    ],
    params: [],
  },
];
